### ISSUE TITLE
Champions mod preventing me from leaving the generating world screen.

### ISSUE THREAD

**Issue by Romoslayer** [TheIllusiveC4/Champions#103]
Whenever I try to generate a new world I get stuck in the generating new world screen and I am unable to get past that even after waiting for multiple minutes. I posted my logs file into the CF support server and it was said that the champion mod "is doing bad java code". I tried generating a new world with the champions mod removed and I was able to generate a world.

Mod Version - champions-forge-1.16.5-2.0.1.8
Forge Version - Forge-1.16.5-36.2.0

Link to Logs File.
https://drive.google.com/file/d/1GhWsv9gjwOFR6Pzu4Gz042c-Aa5rfXAK/view?usp=sharing

**Comment by TheIllusiveC4** [comment]
Did you change your configs at all? Can you share your `champions-ranks.toml` server config file?

**Comment by Romoslayer** [comment]
#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = 16777215
	chance = 1.0
	growthFactor = 0
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 1
	numAffixes = 1
	defaultColor = 16776960
	chance = 0.07
	growthFactor = 0.3
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = 16750848
	chance = 0.05
	growthFactor = 0.7
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 3
	numAffixes = 3
	defaultColor = 6750207
	chance = 0.03
	growthFactor = 4
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 4
	numAffixes = 4
	defaultColor = 13382655
	chance = 0.01
	growthFactor = 8
	effects = []
	presetAffixes = []

**Comment by Romoslayer** [comment]
Any updates on the status of this bug?

**Comment by TheIllusiveC4** [comment]
Sorry for the delay in my response. I was workshopping whether I could solve this a little more elegantly on my end without requiring any changes on your part, but that didn't really pan out.

As for the issue itself, I believe it is because you have `growthFactor = 0.3` and `growthFactor = 0.7` in your ranks configuration. The setting only supports whole numbers (so things like `growthFactor = 1` instead). If you need to increase the stats more incrementally than whole numbers would allow, you should instead adjust the growth amounts for each attribute in the `champions-server.toml` file.

**Comment by Romoslayer** [comment]
I figured that was what was going on, thanks.
