### ISSUE TITLE
Graphical glitches and OpenGL Stack Underflow error logs

### ISSUE THREAD

**Issue by SheReyy** [TheIllusiveC4/Champions#108]
Versions:
* Champions: champions-forge-1.16.5-2.0.1.8.jar
* Forge: 36.2.21

#### Observed Behavior: At random, all the entities become invisible, including you, the player. The latest log says something about
OpenGL stack Underflow.

#### Steps to Reproduce: Happens at random, most probably when a Champion mob spawn nearby

Latest Log (no crash takes place): [Here](https://gist.github.com/IamRyan30/5d00ffbb3f6814bdf93b81d39c710022)

I had a very bad time figuring out what mod was causing this. I noticed that, usually, when I spawned in a mob which had a champion boss bar, all the entities turned invisible. Since I removed Champions, all of my issues were gone.

**Comment by TheIllusiveC4** [comment]
You'll have to narrow down which mod is causing this issue before I can investigate further. I suggest looking at your modlist and taking out half the list at a time to see if the issue can be isolated. To possibly make it easier, you can try taking out any that look like they add a HUD element or mess around with the GUI in some way since that's what is likely causing the issue to occur.

**Comment by SheReyy** [comment]
I reported this issue just so you know about it in case someone else encounters it. I will not try to diagnose this anymore as I've already solved my issue by simply removing Champions.

**Comment by Swifty744** [comment]
I thought I was going insane but yes he's right, I'm having the same issue too. I walk up to an entity with (idk what on perks him) and I go invisible, all the mobs around me do too, I kill myself and the invisiblity stays on, I destroy a block and it's like the game is lagging, no block particles fall or anything. I have to restart a world if I want this to stop. It's a shame because this is one of my favourite mods. Not sure exactly what casuses it because everything goes invisible before I can see what the mob has on it e.g. if it's to do with a specific champion effect I'm not sure. Thanks for the report, I was going insane slowly. haha

**Comment by TheIllusiveC4** [comment]
After some back and forth on Discord and looking at all of the related issues dealing with graphical glitches, I strongly suspect that this issue might be caused by the Advanced Compass mod which seems to be the common thread. I was also able to reproduce some of the issues reported while having that mod installed alongside Champions (though not all of them, no entities turned invisible for example).

However, since it seems to be a difficult issue to reproduce and I am consolidating a few different threads into one, I'd like to ask that anyone experiencing this issue try testing their environment without Advanced Compass installed and report back if the issue either still occurs or you believe the issue to be solved.

In the case of the latter, I do have a potential workaround for those who still wish to use both mods.

**Comment by Ravinhurst** [comment]
I just wanted to add to this after having this same problem while playing the Fantasy Realm modpack.  You are definitely right TheIllusiveC4, this only happens when both Champions and Advanced Compass are installed together.  They don't seem to cooperate well.  For my case, it caused all entities (mobs, beds, chests, enchanting table book, etc) to completely disappear.  The mobs themselves could be killed still, so it is a visual bug only, tho a debilitating one.  This was the first time I have ever experienced this bug, and I have played many a modpack including the Champions mod, but this modpack would be the first one I played that included the Advanced Compass mod.

After experiencing the issue, I temporarily disabled the Champions mod and the problem was fixed, so I searched around to find out why, and to see if maybe there was a fix since I like this mod.  After coming across this, I tried to narrow down what might be causing it, but the only thing that resolved the issue was to disable one of the mods.  I am interested to know the potential workaround you have, but for now I have disabled the Advanced Compass mod since I believe what the Champions mod adds is worth more to me then the compass mod.

**Comment by TheIllusiveC4** [comment]
> I am interested to know the potential workaround you have

If you are indeed experiencing an issue with Advanced Compass and Champions, try going into the configuration file Advanced Compass (`advancedcompass-client.toml`) and setting `moveBossbar = false`.

**Comment by TheIllusiveC4** [comment]
I'll be closing this as, based on all the reports I've received, I do believe all of the graphical glitches are related to the Advanced Compass incompatibility and this will need to be fixed on their end. In the meantime, the workaround I mentioned above will allow users to use both mods without errors.

**Comment by LukaKeres** [comment]
i have the same problem but i dont use advanced compass
