### ISSUE TITLE
Can't get mobs to always spawn as Champions

### ISSUE THREAD

**Issue by LukewarmYeti** [TheIllusiveC4/Champions#11]
I can't seem to get certain mobs except vanilla mobs to **always** spawn as champions. (for this part of the config shown below).

List of mobs that will always spawn as champions
S: "Champion Mobs List"  <
>

#### Versions (Be specific, do not write "latest"):
* Champions: 1.0.4
* Forge: 2806

I've tried various different methods to add mobs to the list in case my formatting was wrong. I assumed it was modid:entityid, e.g. = minecraft:wither_skeleton 

These are the formatting options I've tried for this config

- frostmaw
- mowziesmobs:frostmaw
- [mowziesmobs:frostmaw]
- <mowziesmobs:frostmaw>

Mobs from both Mowzies Mobs & Primitive mobs don't seem to work, however I'm not 100% sure on the formatting still.

Now I tried just = wither_skeleton as well as = skeleton
and that worked, but only for the skeletons that spawned naturally or from a mob spawner. Using spawn eggs in creative didn't apply the champion bonuses. 

Furthermore, the creative "spawn a champion" egg from the mod doesn't seem to do anything for me.

**Comment by TheIllusiveC4** [comment]
I'll do some testing momentarily on the config list.

Note that it's intended behavior that only mobs spawned naturally or from a mob spawner will become champions. Spawn eggs will never spawn champions. This is because these use different spawning methods.

I just tested the "/championegg" command and it executed correctly. What specifically are you entering in to get the egg?

**Comment by LukewarmYeti** [comment]
There's a spawn egg in JEI called "spawn champion" from your mod when you @champions.  I just added it to hand via cheat mode and tried to use it. 

Ah I didn't test the /championegg command. I just realised what that champion egg is for and why it doesn't work.

So testing using the command, 

- vanilla mobs work fine using /championegg skeleton 1 (for example)
- the majoirty of primitive mobs I tested seem to work using the command /championegg primitive:mobs "insert mobsname" "tier"
- it looks like mobs from primitive mobs do get affected by the config (part of the original issue), I just assumed they didn't because I was using spawn eggs to test if it worked.
- using /championegg mowziesmobs:naga (tried most mobs from mowzies) doesn't spawn a mob for me, and natural spawns from mowzies don't get affected by the config. Maybe it's the way they are coded?
- side note, I assume it's either intended (or not possible) for the wither and ender dragon to be champions (due to the way they spawn maybe?)

**Comment by TheIllusiveC4** [comment]
Ah yeah, that explains it. You need to obtain it via command in order to give the egg the correct information, otherwise it's useless.

I'll have to test Mowzie's Mobs to see what's going on there.

You know, I never thought about the Wither and the Ender Dragon. Originally the code used a different hook so they could definitely become champions, but now I'm not sure. Probably not? I'll definitely have to look into this. It's intended that it's possible for them to become champions.

**Comment by TheIllusiveC4** [comment]
Alright, so I've pretty much concluded my work on this issue. Here's the results:

1. I've added in a fallback for all "unnatural" spawns, so that they can be champions too. This should round out various issues for fringe cases and also definitely includes the Wither and the Ender Dragon now. This also re-enables spawn eggs being able to spawn champions, so you can use that for further testing if necessary. These changes will appear in the next update.

2. Mowzie's Mobs: The reason that their mobs don't work with the config is because their mobs can't spawn as champions at all and _that_ is because they don't actually label them as mobs (read: they do not implement the IMob interface that all vanilla mobs and many modded mobs do).

**Comment by LukewarmYeti** [comment]
Understood, thanks for looking at the issue for me. I appreciate how quickly you clean up bugs/issues with all your mods.
