### ISSUE TITLE
[Suggestion] Scaling Health's difficulty affecting the likehood of a Champion to spawn as well as their tiers.

### ISSUE THREAD

**Issue by Z-Tunic** [TheIllusiveC4/Champions#13]
Unsure if this mod or the mod author for Scaling Health has to add in support but I figure it could be a neat idea to see if Scaling Health's Difficulty could affect the likehood of a Champion spawning as well as affecting their tiers.

For example... at 50 difficulty... champions are more likely to spawn with the possibility of being at higher tier than with 0 difficulty and if at 250 difficulty which is scaling health's default value... if I recall... champions could be quite common and at their highest tier than with a low tier.

There's also a chance for the Champion to become a Blight since Scaling health gives the chance for mobs to become Blights with the odds increasing as the difficulty rises... that is if you get unlucky with the spawn. They are quite a scary thing that's for sure.

Options could be configurable if you want it reasonable... or wanna be evil if difficulty was at 500 and you want champions to spawn 100% of the time.

**Comment by TheIllusiveC4** [comment]
I think support could be added from either end, but I guess the responsibility might as well fall to me since I'm already addressing this issue by writing this comment.

It should be possible but the actual implementation to get the right amount of configuration could be tricky from an end-user perspective if done haphazardly. I'll have to look into this first.
