### ISSUE TITLE
Information Request

### ISSUE THREAD

**Issue by Saereth** [TheIllusiveC4/Champions#137]
#### Versions (Be specific, do not write "latest"):
* Champions: champions-forge-1.18.2-2.1.6.0.jar
* Forge: 40.1.80

with the addition of game staging how does it work if I have a mob that is set to always be a tier 2 but I have a gamestage set for t2 and the player doesnt have the stage? Will my config setting override the gamestage or will the gamestage override the mob setting

**Comment by TheIllusiveC4** [comment]
Well, currently, what would happen is that your config setting will override the game stage. That mob will still be able to spawn as a tier 2 because that's what it will always be.

But, thinking about it, I wonder if that's right? In this situation, should the mob instead spawn as no champion if the player doesn't have the stage for its minimum tier?

**Comment by Saereth** [comment]
I think from a packdev standpoint if we always want a certain mob to be a champion so much that we go out of our way to set it in the config it should probably take precedent over the tiered game stage which is more generalized so it sounds like the current implementation is the way I'd hope for it to work.

**Comment by TheIllusiveC4** [comment]
Okay, that seems fair. I'll leave the implementation as it is then.
