### ISSUE TITLE
[1.12.2] Infested Champions with high Health will cause quite an FPS drop as they summon an army of Silverfish for any damage they take.

### ISSUE THREAD

**Issue by Z-Tunic** [TheIllusiveC4/Champions#17]
I don't suppose there could be a way to have the silverfish despawn after some time if they were summoned from an Infested Champion? Or put some sort of cap to how many silverfish they can spawn before they can't spawn anymore?

With the default config the "Silverfish per Attack" is set at 1 and apparently this could cause some FPS drops since the silverfish don't seem to despawn after some time, even if you kill their host.

By normal means... a Zombie for example has 20 health but if paired with Scaling Health since that allows you to increase Mob health depending on the difficulty... silverfish will spawn from ANY attack meaning that if the mob has... I dunno 5000 health for example and it gets damaged by lava or some other damage source... that's going to be a lot of silverfish that will be summoned when left alone in a cave or something.

I know I can just set "Silverfish per Attack" to 0 to avoid this from happening but... eh.

**Comment by TheIllusiveC4** [comment]
I'll see what I can do to fix/mitigate this.

**Comment by TheIllusiveC4** [comment]
What I've done is limit the silverfish spawning on damage taken to only trigger when that damage is from a living entity. This should mitigate situations where they spawn uncontrollably when there's no one even attacking it (aka lava or something environmental). In addition, if that's not enough, I've added it as its own config option "Silverfish on Damage Taken" so that this value could be set separate from the "Silverfish per Attack" value.

**Comment by DatrixTHLK** [comment]
Hi,

Is it normal to have this many entites spawning into your game after attacking each of the silverfish within minecraft? minecraft 1.12.2 (Champions 1.0.8). (forge 14.23.5.2824) 
![2019-03-30_21 36 03](https://user-images.githubusercontent.com/13172036/55283612-21fb4c00-5335-11e9-859d-d2a262d87109.png).

**Comment by TheIllusiveC4** [comment]
You'll have to be a little more specific about what's triggering the increased spawn rate. Infested is not triggered by environmental damage, so something is attacking them over and over somehow. In addition, I'll have to test this to make sure it's working right, but Infested specifically blacklists Silverfish and Endermites from spawning with the affix at all. In addition, Silverfish/Endermites spawned from the Infested affix are specifically coded to never become champions (although this can be bypassed if, for instance, Silverfish crawl into a stone block and then respawn back later).

It would be helpful if you could reproduce your scenario and then tell me the same steps so I can reproduce it and see how it's happening.

**Comment by DatrixTHLK** [comment]
What I'm trying to say is that I'm the culprit. I attacked them and they spawned in not that many at first but after I attacked the silverfish more started spawning in until that happened in the picture. They never broke stone in order to spawn in though, just out of thin air. I will take a look into the config options again and see where that option is. Thanks for the info.
