### ISSUE TITLE
Mobs spawners "Roguelike Dungeons"

### ISSUE THREAD

**Issue by Xitryne** [TheIllusiveC4/Champions#29]
#### Versions (Be specific, do not write "latest"):
* Champions: champions-1.12.2-1.0.10.1.jar
* Forge: forge1.12.2-14.23.5.2838

#### Expected Behavior: The mobs spawners of the mod "Roguelike Dungeons" are modified mobs appear with armor which could disrupt the config file of mod "champions"

If you could make sure there is no conflict with this mod it would be great, otherwise great job nothing to say!
(Sorry I had to use google translation)
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
I believe this is due to Roguelike Dungeons not implementing/respecting the Forge event `LivingSpawnEvent.SpecialSpawn` which is how Champions knows whether the spawn is from a mob spawner or not. In this case, there's not much I can do on my end and this will have to be addressed from the Roguelike Dungeons developer.
