### ISSUE TITLE
You can add a Champions mob ai?

### ISSUE THREAD

**Issue by Abo233** [TheIllusiveC4/Champions#31]
#### Versions (Be specific, do not write "latest"):
* Champions:
* Forge:

#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by Abo233** [comment]
Defult: followRange :20
Describe：1.By Level Add followRange：20 for each step up
                 2.Let them can Breaking block 
 
 
Because the monsters look so stupid.
I hope you 'll take it.

**Comment by TheIllusiveC4** [comment]
1) I might consider some sort of follow range upgrade as a general champion buff.
2) I don't really like abilities that can grief a player or upset their builds in any way.
3) The problem with having abilities tied to having other monsters around is that they become useless when they're alone and overpowered when it's crowded. There's too much variability there. In addition, summoning monsters gets tricky because it's hard to tell, in modded, exactly which monsters are safe to summon in this manner.
