### ISSUE TITLE
Log gets spammed with STDERRs

### ISSUE THREAD

**Issue by ireece1** [TheIllusiveC4/Champions#35]
* Champions: champions-1.12.2-1.0.11
* Forge: 14.23.5.2847

Something to do with rendering the champion health. This happen's every now and then

Crash Log: https://pastebin.com/jz09NMqm

**Comment by TheIllusiveC4** [comment]
I can't reproduce this issue. It seems like it's saying that the distance between the viewing player and the champion is too large. However, I've tried with up to 100 blocks viewing distance which translates to a bounding box much much larger than the one that gave you an error and it doesn't give me anything in the logs.

Even stranger, I can't even find where it is throwing that error in the Minecraft code at all. It seems like it shouldn't even be possible to get that error.

Regardless, I don't think there's anything I can do about this since it's necessary in order to identify what champion you're looking at. The best solutions I can think of is to either set the config option for health bar visibility to a low enough number that won't trigger this anymore or disable the champion HUD entirely (which is a feature that I plan to include in the next build).
