### ISSUE TITLE
Interaction with Ice & Fire Dragons

### ISSUE THREAD

**Issue by Goatwright** [TheIllusiveC4/Champions#49]
#### Versions (Be specific, do not write "latest"):
* **Champions:** champions-1.12.2-1.0.11.8.jar
* **Ice & Fire:** iceandfire-1.9.1-1.12.2
* **Forge:** 14.23.5.2854

#### Observed Behavior:
Attempted to add the dragons from the Ice & Fire mod to the list of mobs that'll always spawn as Champions, but I've been unsuccessful in getting any to become one. Any other mob related to the mod (cyclops, gorgons, hydras) successfully spawned as Champions.
#### Expected Behavior:
Expected the dragons to become Champions. I'm guessing it has to do with the unusual way that the entities are handled (with their 'stages') but I have no clue how to resolve the issue. I tried allowing them to create a Champion from spawners thinking that might be how they're brought in with their nests, but to no avail. 
#### Steps to Reproduce:
1. Install Ice & Fire and Champions
2. Input dragons' mob entity into Champions config file. (iceandfire:firedragon and iceandfire:icedragon respectively.) 
3. Find a dragon in the wild or use a spawn egg to create a dragon.
4. See no relevant change to the entity.

**Comment by TheIllusiveC4** [comment]
This is because Ice and Fire does not label them as hostile mobs. Only hostile mobs can ever become champions, regardless of configs. They're labeled as tameable mobs, like wolves, ocelots, and parrots.

Unfortunately, the only two solutions for your situation that I can see are either I allow tameable mobs to be champions or Ice and Fire relabels the dragons. For the former, I don't want to make any large changes to Champions for 1.12.2 as it's very stable as it is and I'm not entirely sure it's a good idea to allow champion effects on tameable mobs. For the latter, I'd imagine it'd take a lot of effort on their end to change that and they probably did so in the first place for a good reason.
