### ISSUE TITLE
[1.15.2] NBT with /champions command

### ISSUE THREAD

**Issue by mr-poyo** [TheIllusiveC4/Champions#51]
Hello,

Is there a way we could add NBT information alongside the /champions summon command? 

Currently to achieve this, I summon a champion with /champions summon, then I /data merge afterwards with NBT additions. 

Would be cool if we could add NBT information alongside the /champions summon and summonpos commands. 

For example:
`/champions summon minecraft:zombie 2 {Team:"poyoteam",Tags:["testtag"],CustomName:'{"text":"Hello!"}',ActiveEffects:[{Id:10b,Amplifier:1b,Duration:199980}],Attributes:[{Name:generic.attackDamage,Base:20}]}`

I used mcstacker to generate the NBTs easier as an example. Thank you!

**Comment by Boolyman** [comment]
This would be nice.

**Comment by TheIllusiveC4** [comment]
This is now possible as of the latest 1.16.5 and 1.18.2 updates. Due to various reasons, summoning with NBT and Champions requires using the regular `/summon` command in conjunction with special NBT tags to denote champion stats like rank and affixes. Please see the full documentation [here](https://docs.illusivesoulworks.com/1.18.x/champions/nbt) for details.
