### ISSUE TITLE
[1.12.2] Feature Request

### ISSUE THREAD

**Issue by vizthex123** [TheIllusiveC4/Champions#53]
I love the mod, but was wondering if you could add a feature to the config of the 1.12.2 version that lets you remove the pre-made champion titles.

I use this mod in my new story-based pack and the champions are supposed to be elite members of the villain's army, so having "Drinker of Blood" and other titles/names kind of goes against that lore.

Thanks.

**Comment by TheIllusiveC4** [comment]
So, unfortunately, I won't be implementing a fully realized feature for this. This is because the 1.12.2 version is technically only in maintenance mode right now. Also, the 1.14+ port removes the naming feature entirely so it gets deprecated anyways. However, I have tried to help you out a bit and I've implemented a client-side config option that can remove the names from being rendered. That way players won't really see it, unless they dig into it and really want to.

**Comment by vizthex123** [comment]
Well, I wanted to have my custom ones render instead of the default....I had hoped the 1.12.2 version was still being supported, but I guess not.

It's not a huge deal at least, just something I thought would be nice to have.

**Comment by TheIllusiveC4** [comment]
If you just wanted to replace them, can you not provide a resource pack that overrides the names? All of the names just come from the lang file.

**Comment by vizthex123** [comment]
I guess I could, I just have no idea how to do that

**Comment by TheIllusiveC4** [comment]
The Minecraft wiki pretty much has all of the info you need
https://minecraft.gamepedia.com/Resource_Pack

**Comment by vizthex123** [comment]
Well, I guess I can see if it works. Thanks.
