### ISSUE TITLE
[1.16.1] Crash to desktop

### ISSUE THREAD

**Issue by BedrockLegends** [TheIllusiveC4/Champions#54]
#### Versions (Be specific, do not write "latest"):
* Champions: champions-FORGE-1.16.1-2.0-beta6.jar
* Forge: 32.0.75

#### Observed Behavior:
 Logged into a single player world and crashed straight to desktop
#### Expected Behavior:
Hopefully a quick fixs
#### Steps to Reproduce:
1. installed
2. Launched
3. Joined world and crashed
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

https://gist.github.com/BedrockLegends/62a6213e0215fe897c7e5666c6c2c438

**Comment by TheIllusiveC4** [comment]
So there is an easy way for me to fix this, but there's something wrong with your environment. Do you have `champions-ranks.toml` in your world's `serverconfigs` folder?

**Comment by BedrockLegends** [comment]
@TheIllusiveC4 This was on single player, I did not test on server

**Comment by TheIllusiveC4** [comment]
Single player worlds still have a `serverconfigs` folder in the world save folder. Please check there and make sure that `champions-ranks.toml` is there (along with the three other champion config files).

**Comment by BedrockLegends** [comment]
@TheIllusiveC4 they are not, but I really do not want to reset my world to gen them

**Comment by TheIllusiveC4** [comment]
You don't need to reset your world, you just need to make those files yourself. Here's the thing though, your environment is not generating the configs for some reason. This is a problem, because whether or not I solve your crash issue, your world will not have the right configs because they do not exist. You will need to find out why your environment is not generating those configuration. I've tested this myself and I can generate them just fine. Do you have the server configuration for other mods generating?

**Comment by BedrockLegends** [comment]
Yes I do, But I never use them for anything

**Comment by TheIllusiveC4** [comment]
Well, I don't know why your Champions configs aren't generating then. Sorry. The best I can do is prevent the crash from happening and give you the default files that should be generating. 
[champions-configs.zip](https://github.com/TheIllusiveC4/Champions/files/4958314/champions-configs.zip)
