### ISSUE TITLE
Suggestions and questions

### ISSUE THREAD

**Issue by Akitori** [TheIllusiveC4/Champions#7]
I'm curious, why remove things like beacons prevent champions, champions copying reflected damage, etc?

Idk, personally i liked some of the changes (champions and beacons is great in my opinion, useful for bases/spawnpoints)

**Comment by TheIllusiveC4** [comment]
I removed the beacons preventing champions thing because it had a somewhat limited range and not really sure it was useful to anyone. It was just something I kinda added off-hand during development and never really thought about. If you like it, I can certainly add it back in.

Champions do still copy reflected damage, it's just that its name is different. For instance, if the original damage was fire damage, it will still throw back fire damage, it's just identified differently internally. This change was due to https://github.com/TheIllusiveC4/Champions/issues/6 being brought up about problems that may occur due to using the exact same identifier for reflected damage, and I think this results in overall better behavior personally.

**Comment by Akitori** [comment]
I like the beacons frankly, even in just basic concept. 

Ah, i was unsure if the reflected damage was changed to something else outright.

One suggestion I would like is something to negate plague a bit. I'm pretty sure milk buckets could work, but having to drink a entire stack while fighting a zombie with a lot of health seems a bit silly.  I do however like how it sticks to you, which is cool.

Is it bad I want more projectile based boosts? Ex: Faster arrows/blaze shots? or more damaging?

**Comment by TheIllusiveC4** [comment]
Milk Buckets would definitely work, if necessary. Note that Plague has a very limited range (about 3 blocks), so the main intent is that you'd ideally be fighting from a ranged position to avoid the plague effect entirely. I feel like having a way to negate it any further would diminish its efficacy too much.

I'm up for more projectile-based affixes, but it's very tricky all things considered. For instance, faster/more damaging projectiles is difficult to implement because it's not easy to figure out which mobs actually have a projectile attack in addition to the question of whether or not I can hook into that to change its behavior. Also, as a design tenant, I avoid any abilities that are already used by mobs so stuff like Ghast and Blaze fireballs are out. The simplest way is to come up with entirely new projectiles to add to mobs, though this comes with the design difficulty of figuring out one that is both unique and strategic.

**Comment by Akitori** [comment]
I see. Well that explains why plague hurts me so much, i typically go into melee range for most mobs.

Hooking to all mobs would be difficult, yeah. Well, one of the few projectile abilities i would like to see is something that diminishes the attack of the player, or gives them blindness. Range is usually the most viable option to take out most mobs, so why not some projectile that makes range a bit more difficult?

**Comment by TheIllusiveC4** [comment]
I've thought about a blindness sort of attack a lot. I was reluctant to add that in because I felt like that made attacking ranged mobs too difficult. But I didn't consider it as a projectile attack, which is an interesting option. I'll have to workshop that idea a bit more. Even if that doesn't work out, I'll try to figure out something that will primarily trouble ranged attackers.

**Comment by TehSeph** [comment]
IIRC, when you spawn a mob in forge you can specify a mainhand and offhand weapon. Why not just give all spawned champions with ranged attacks a bow in their mainhand?

**Comment by Akitori** [comment]
Not all projectiles use bows. Also, changing equipment on a mob with other mods present could invite some people to blame Champions.

**Comment by TheIllusiveC4** [comment]
@TehSeph Yes, actually, here you go: [https://discord.gg/JWgrdwt](https://discord.gg/JWgrdwt)

On-topic, to add to Akitori's point, it's also hard to know what might happen if you try to give certain equipment to some mobs, especially in the world of modded Minecraft. As a more superfluous reason, it might also just look silly on some mobs.
