### ISSUE TITLE
Crash when entering the world after changing the lootconfig

### ISSUE THREAD

**Issue by ly943030208** [TheIllusiveC4/Champions#70]
Hello,I am a Chinese and communicate with you with the help of translation software.
Champions: 1.16.4-2.0.0.2
Forge: 1.16.3 35.1.32
I  changed the lootcofig.The relevant code:
#Set the source of champion mob drops
	#Allowed Values: CONFIG, LOOT_TABLE, CONFIG_AND_LOOT_TABLE
	lootSource = "CONFIG_AND_LOOT_TABLE"
	#Set to true to allow fake players to generate champion loot
	fakeLoot = true
	#List of loot drops from champions if sourced from config
	#Format: [tier];[modid:name];[amount];[enchant(true/false)];[weight]
	lootDrops = [1;minecraft:diamond;1;false;1]
	#Set to true to scale amount of loot drops from champions to tier if sourced from config
	lootScaling = true
       But when I do this, I can’t enter the world.I hope you can pay attention to this issue. Thank you！

**Comment by ly943030208** [comment]
Sorry,forge vesion is 1.16.4 35.1.32

**Comment by TheIllusiveC4** [comment]
Hello, I cannot speak Chinese so I will also use translation software to communicate with you.

I believe your problem comes from `lootDrops = [1;minecraft:diamond;1;false;1]`. 

There should be quotation marks around each value.

`lootDrops = ["1;minecraft:diamond;1;false;1"]`

If this doesn't solve your issue, please share the crash report with me.

您好，我不会说中文，因此我还将使用翻译软件与您交流。

我相信您的问题来自`lootDrops = [1;minecraft:diamond;1;false;1]`。

每个值周围应带有引号。

`lootDrops = ["1;minecraft:diamond;1;false;1"]`

如果这不能解决您的问题，请与我分享崩溃报告。

**Comment by ly943030208** [comment]
Thanks a lot!
