### ISSUE TITLE
Change default rank config to chance = 0.0 for tiers higher than 1 [QoL Suggestion]

### ISSUE THREAD

**Issue by Lystraeus** [TheIllusiveC4/Champions#76]
This is aimed at DIY users. Skips the surprise of that one-shotting skeleton ending a hardcore run (RIP)

**Comment by TheIllusiveC4** [comment]
This seems a bit like a quality of life deterioration to me. The default rank config is set up with initial settings so that most users can simply add Champions into their environment without any configuration. Changing the default chance for tiers higher than 1 would force every user to go into the configuration to activate higher tiers, which is one of the core aspects of the mod. And it doesn't make anything easier for DIY users who are going into the configurations anyways.
