### ISSUE TITLE
Can't figure out how to set 1.16.5 config loot drops

### ISSUE THREAD

**Issue by TheZetifate1745** [TheIllusiveC4/Champions#80]
I can't figure out how to use config loot drops. In the config it shows #Format: [tier];[modid:name];[amount];[enchant(true/false)];[weight].  I tried that then tried other ways to do it. I also don't know how to set multiple different items and for different tiers of champions. Also how much does loot scaling scale it by per tier and if enchant is true will it put something like efficiency on a sword?

**Comment by TheIllusiveC4** [comment]
You need to share what you tried, otherwise I don't know what you've done already or what you did wrong.

Loot Scaling gives the same number of drops as the tier. So tier 1 will drop 1, tier 2 will drop 2, and so on.

If enchant is true, it just randomly enchants using the same logic as vanilla for enchanting items. It wouldn't put Efficiency on a sword because that's not a valid enchantment combination.

**Comment by TheZetifate1745** [comment]
> You need to share what you tried, otherwise I don't know what you've done already or what you did wrong.
> 
> Loot Scaling gives the same number of drops as the tier. So tier 1 will drop 1, tier 2 will drop 2, and so on.
> 
> If enchant is true, it just randomly enchants using the same logic as vanilla for enchanting items. It wouldn't put Efficiency on a sword because that's not a valid enchantment combination.

I tried
[1];[minecraft:iron_nugget];[1];[enchant(true)];[1]
[1;minecraft:iron_nugget;1;enchant(true);1]
I also tried those two with "minecraft:iron_nugget" and enchant:true and just true in the enchant part. Could you give an example of a working loot config for two items.

**Comment by TheIllusiveC4** [comment]
Example of two items:
```
lootDrops = ["1;minecraft:iron_nugget;1;true;1", "1;minecraft:diamond;1;true;1"]
```
