### ISSUE TITLE
Champions title names aren't changing

### ISSUE THREAD

**Issue by Xablauzero** [TheIllusiveC4/Champions#88]
#### Notice
The champions Ranks Name aren't loading when i'm using my resourcepack. Stills the default names and rank.champions.title.5 at Rank 5, i tried everything but didn't seemed to work. 

#### Versions:
* Champions: 2.0.1.7
* Forge: 36.1.23

#### Observed Behavior: 
The champions mobs still have the default rank names.

#### Expected Behavior: 
Rank names should be changed.

#### Steps to Reproduce: 
1. Download this resourcepack: [resources.zip](https://github.com/TheIllusiveC4/Champions/files/6759882/resources.zip)
2. Put it on your maps folder.

If there's an Resourcepack with changed names, then i would appreciate if possible to send.

**Comment by TheIllusiveC4** [comment]
A few issues:

1) I'm not sure what you mean by `maps` folder. Resource packs should go into the `resourcepacks` folder.
2) The namespace should be `champions`, not `minecraft`.
3) The lang file should be named `en_us.json`, not `en_US.json` (not sure if this matters but it's something to note).
4) The format of your files do not adhere to json structure. See [here](https://github.com/TheIllusiveC4/Champions/blob/1.16.x/src/main/resources/assets/champions/lang/en_us.json) for an example using the standard lang file from Champions.

I've taken the liberty of making the proper changes to your pack here:
[resources.zip](https://github.com/TheIllusiveC4/Champions/files/6761701/resources.zip)

Please download it, take note of my points above and the changes I made in order to understand the proper way to override the titles. Let me know if you have any more questions.

**Comment by Xablauzero** [comment]
> A few issues:
> 
> 1. I'm not sure what you mean by `maps` folder. Resource packs should go into the `resourcepacks` folder.
> 2. The namespace should be `champions`, not `minecraft`.
> 3. The lang file should be named `en_us.json`, not `en_US.json` (not sure if this matters but it's something to note).
> 4. The format of your files do not adhere to json structure. See [here](https://github.com/TheIllusiveC4/Champions/blob/1.16.x/src/main/resources/assets/champions/lang/en_us.json) for an example using the standard lang file from Champions.
> 
> I've taken the liberty of making the proper changes to your pack here:
> [resources.zip](https://github.com/TheIllusiveC4/Champions/files/6761701/resources.zip)
> 
> Please download it, take note of my points above and the changes I made in order to understand the proper way to override the titles. Let me know if you have any more questions.

Oh sorry, really sorry! I didn't know that the champions mod uses an different method at the language file. Also, about the maps part, if you just add a .zip called resources in an maps folder, will automatically loads at the top of all other resources, so that's why i made it at the maps folder. 

Btw, really thanks for all the help, i really appreciate then!
