### ISSUE TITLE
Lycanite Mobs not affected by Champions' Attribute Changes

### ISSUE THREAD

**Issue by Xaikii** [TheIllusiveC4/Champions#9]
#### Versions (Be specific, do not write "latest"):
* Champions: 1.12.2-1.0.2
* Forge: forge-14.23.5.2796
* Lycanite's Mobs: 1.20.5.1

#### Observed Behavior:
Checked with Health, Health never changed for any Lycanite's Mobs Mob, yet did for any other Mob.

#### Expected Behavior:
Lycanite's Mobs Mob's Health being higher with a higher Tier.

#### Steps to Reproduce:
1. Put Lyca's Mobs + Champions in 1 Pack
2. Change Champion Settings so you can test properly
3. Observe

I assume this happens due to the Way Lyca registers his Mobs.
Also the Health Factor has been 0.125 and Rank 1 had as Multiplier 1
[https://imgur.com/a/KhtpfeU](https://imgur.com/a/KhtpfeU)

**Comment by TheIllusiveC4** [comment]
I did some testing and Lycanite's Mobs mobs are spawned from Champions with the correct health. However, this health somehow gets reset each tick back to its original amount. I'm not sure how Lycanite's Mobs is updating its mobs but I suspect that this is something that should be solved on their end if possible, especially since I have not received word of this being a problem with any other mob.

Open up an issue with that developer and see what they say. If the issue comes back to my end, I'll take another look at it.

**Comment by Xaikii** [comment]
ok, thanks :)

**Comment by Xaikii** [comment]
Just wanted to update this thread, the bug was fixed by Lycanite
